### ISSUE TITLE
ImportError: No module named 'lcoreapi'

### ISSUE THREAD

**Issue by itJunky** [CCrypto/ccvpn3#3]
```
root@debian-test:~/ccvpn3# ./manage.py createsuperuser
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/usr/local/lib/python3.5/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.5/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.5/dist-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/root/ccvpn3/lambdainst/models.py", line 11, in <module>
    from . import core
  File "/root/ccvpn3/lambdainst/core.py", line 2, in <module>
    import lcoreapi
ImportError: No module named 'lcoreapi'
```

**Comment by itJunky** [comment]
May be in instreuction need to say 
pip3 install --user git+git://github.com/PacketImpact/lcoreapi.git
because pip by default linked to pip2

**Comment by 0xa** [comment]
it requires python 3, the default python version used by "pip" depends on your system.

**Comment by itJunky** [comment]
pip3 is not default! pip2 is default on many systems, but pip3 exist only if python 3 installed!

**Comment by Cubox-** [comment]
Hello itJunky.

Thanks for your interest in our project, the reason we publish and keep an organised and documented repository is to share how our service works.
This effort has many reasons, such as having our customers be able to check the source code that runs their accounts, and their VPN connections. We also like to give back to the open source community that we use and love. There are many others reasons I cannot list here.

However, this repository is not meant as a "plug and play" solution. We never intended building this code that anyone would be using it unedited. If the documentation is lacking, or incorrect, you are welcome to help us correct it. However this is not meant to be used to the untrained eye.

Thanks for understanding. Feel free to drop an email if you want to chat a bit more cubox@cubox.me

**Comment by Cubox-** [comment]
Fixed by https://github.com/CCrypto/ccvpn3/commit/98b41e144eb0526f39ed9c13d52ae98329b74439
